# NumPy Array


Numpy array is much faster than list and take less memoray but cannot store values of diff datatypes

# Import Numpy Library to creat array
While in list we can directly create and perform operations


In [1]:
import numpy as np #np is standard alias for convinience for using numpy  operations

# Lets create array in numpy

In [22]:
X=np.array([1,2,3,4,5,6])

In [23]:
print(X)

[1 2 3 4 5 6]


# Lets create List and print it as np.array


In [ ]:
l=[]
for i in range(1,5):
 int_i=int(input("Enter an integer"))
 l.append(int_i)
 print(np.array(l))

# 2-dimensional Array

In [ ]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y.ndim)

# 3-dimensinal array

In [ ]:
Z=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
print(Z)
print(Z.ndim)
A=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A)
print(A.ndim)

# Arrays elements filled with Zero's

In [ ]:
arr_zero=np.zeros(8)
print(arr_zero)   #1 dimensional
print()
arr2_zero=np.zeros((2,4))
print(arr2_zero) #2-dimensional
print()
arr3_zero=np.zeros((2,4,6))
print(arr3_zero) #3-dimensional

# Arrays elements filled with ones

In [ ]:
arr_one=np.ones(8)
print(arr_one)   #1 dimensional
print()
arr2_one=np.ones((2,4))
print(arr2_one) #2-dimensional
print()
arr3_one=np.ones((2,4,6))
print(arr3_one) #3-dimensional

# Empty array takes the random updated values in the memoray

In [6]:
arr_emp=np.empty(4)
print(arr_emp)
print()
arr_emp2=np.empty((2,4)) #2d empty array
print(arr_emp)
print()
arr_emp3=np.empty(((2,3,4))) #3d empty
print(arr_emp)
print()


[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.07876653e-311]

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.07876653e-311]

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.07876653e-311]



# Full array full((shape range)value stored)

In [9]:
arr_full=np.full((2,3),4) #2d full
print(arr_full)
print()


[[4 4 4]
 [4 4 4]]



In [11]:
arr_diag=np.eye(3,4)
print(arr_diag)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# Array with values that are linearly spaced linearly in a specified interval

In [13]:
arr_lsp=np.linspace(2,3,4) #2d full
print(arr_lsp)
print()


[2.         2.33333333 2.66666667 3.        ]



# Use Random functions to generate random values in array

Rand() generate vlues between 0 to 1

In [17]:
arr_rd=np.random.rand(5)
print(arr_rd)
print()
arr_rd_2d=np.random.rand(5,4)
print(arr_rd_2d)
print()
arr_rd_3d=np.random.rand(5,2,2)
print(arr_rd_3d)

[0.52266263 0.28957818 0.52918934 0.51451872 0.53845373]

[[0.5851453  0.37881543 0.66961287 0.41475249]
 [0.68346521 0.15426514 0.22247325 0.05006365]
 [0.07994733 0.94099821 0.79154099 0.23073973]
 [0.38095763 0.3407326  0.18715136 0.78099006]
 [0.92005009 0.59613222 0.751286   0.99547991]]

[[[0.04715526 0.33797806]
  [0.9599863  0.70631198]]

 [[0.39389903 0.49132098]
  [0.38745655 0.5168348 ]]

 [[0.61938114 0.49451488]
  [0.95177177 0.13856566]]

 [[0.88364951 0.75656252]
  [0.32839134 0.13448563]]

 [[0.80732892 0.2709396 ]
  [0.22112061 0.73502546]]]


Randn() generate numbers closer to 0 could be negative

In [18]:
arr_rd=np.random.randn(5)
print(arr_rd)
print()
arr_rd_2d=np.random.randn(5,4)
print(arr_rd_2d)
print()
arr_rd_3d=np.random.randn(5,2,2)
print(arr_rd_3d)

[-0.04482198  0.88836079 -0.51068559  0.14691697  0.12914777]

[[ 1.10999528 -0.37933556  0.12403662  0.25061095]
 [ 0.05649989 -1.05504022  0.33192547  0.56513453]
 [ 0.42423445  0.1913787  -1.4870452   0.33868072]
 [ 1.14351747  0.76148154 -0.2537176  -1.43299566]
 [-0.90195746  1.59628975  1.35377683  0.57347659]]

[[[-0.66705005  0.03395227]
  [ 0.42841836  1.40518373]]

 [[ 1.36133585  0.39841517]
  [ 0.2648323   0.45457003]]

 [[-1.26406905 -1.21611115]
  [ 0.36269313 -0.25615528]]

 [[-0.21144958 -1.57548011]
  [ 0.71616587  0.18205078]]

 [[-0.23952836  1.30377098]
  [ 0.73788523 -0.07112018]]]


Ranf() generate random numbers in float [0.0 to 1.0) 1.0 not included only take 1 argument

In [20]:
arr_rd=np.random.ranf(5)
print(arr_rd)
print()


[0.51854444 0.44140662 0.076252   0.6766556  0.6364043 ]



In [ ]:
Randint(min,max,total_values) generate random numbers

In [27]:

arr_rd=np.random.randint(0,2,2)
print(arr_rd)

[1 0]


# **Arithematic Operations in Numpy Arrays**

add(a,b)

In [30]:
arr_add=np.array([1,2,3,4,5])
arr_add2=np.array([4,3,2,1,5])
print(arr_add+arr_add2)

[ 5  5  5  5 10]


subtract(a,b)

In [36]:
arr_sub=np.array([1,2,3,4,5])
arr_sub2=np.array([4,3,2,1,5])

print(arr_sub-arr_sub2)
print(np.subtract(arr_sub,arr_sub2))

[-3 -1  1  3  0]
[-3 -1  1  3  0]


**Divide(a,b)**

In [39]:
arr_div=np.array([1,2,3,4,5])
arr_div2=np.array([4,3,2,1,5])
print(arr_div/arr_div2)
print(np.divide(arr_div,arr_div2))

[0.25       0.66666667 1.5        4.         1.        ]
[0.25       0.66666667 1.5        4.         1.        ]


**Modulus(a,b)**

In [40]:
arr_mod=np.array([1,2,3,4,5])
arr_mod2=np.array([4,3,2,1,5])
print(arr_mod%arr_mod2)
print(np.mod(arr_mod,arr_mod2))

[1 2 1 0 0]
[1 2 1 0 0]


**Reciprocal(1/a)**

In [41]:
arr_rec=np.array([1,2,3,4,5])
arr_rec2=np.array([4,3,2,1,5])
print(1/arr_rec)
print(np.reciprocal(arr_rec2))

[1.         0.5        0.33333333 0.25       0.2       ]
[0 0 0 1 0]


**Same works with 2d array**

In [43]:
arr_mod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr_mod2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(np.mod(arr_mod,arr_mod2))


[[0 0 0 0 0]
 [0 0 0 0 0]]


**FOR 3-D ARRAY**

In [44]:
arr_mod=np.array([[[1,2,3,4,5],[1,2,3,4,5],[2,4,5,6,4]]])
arr_mod2=np.array([[[1,2,3,4,5],[1,2,3,4,5],[2,4,5,6,4]]])
print(np.mod(arr_mod,arr_mod2))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


# **Arithmetic functions**

**min max according to row  axis=1 evaluate the min/max of each column across each row and column axis=0 whic is also default axis**

In [57]:
arr_mod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr_mod2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(np.min(arr_mod,axis=0),np.argmin(arr_mod)) #argmin/argmax to find index
print()
print(np.min(arr_mod2,axis=1),np.argmin(arr_mod2))
print()
print(np.max(arr_mod,axis=1),np.argmax(arr_mod))
print()
print(np.max(arr_mod2,axis=0),np.argmax(arr_mod2))

[1 2 3 4 5] 0

[1 1] 0

[5 5] 4

[1 2 3 4 5] 4


**Sqrt() function**

In [58]:
arr_mod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr_mod2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(np.sqrt(arr_mod))
print()
print(np.sqrt(arr_mod2))


[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.         1.41421356 1.73205081 2.         2.23606798]]

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.         1.41421356 1.73205081 2.         2.23606798]]


**Cos,Sin**

In [60]:
arr_mod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr_mod2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(np.cos(arr_mod))
print()
print(np.sin(arr_mod2))
print()
print(np.cumsum(arr_mod2))

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]]

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]]

[ 1  3  6 10 15 16 18 21 25 30]


# Shape function

In [8]:
arr_sh=np.array([[1,2],[1,2]])
print(arr_sh)
print()
print(f'shape of array {arr_sh.shape}')

[[1 2]
 [1 2]]

shape of array (2, 2)


In [11]:
arr_sh=np.array([1,2,1,2],ndim=4)
print(arr_sh)
print()
print(f'shape of array {arr_sh.shape}')

[[[[1 2 1 2]]]]

shape of array (1, 1, 1, 4)


# Reshape function

In [27]:
arr_sh1=np.array([1,2,1,2,4,6,8,3,5])
print(arr_sh1.ndim)
print(arr_sh1)
print()
X=arr_sh1.reshape(3,3)
print(X)
print()
print(X.ndim)

1
[1 2 1 2 4 6 8 3 5]

[[1 2 1]
 [2 4 6]
 [8 3 5]]

2


In [29]:
arr_sh3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr_sh3.ndim)
print(arr_sh3)
print()
X1=arr_sh3.reshape(2,3,2)
print(X1)
print()
print(X1.ndim)

one_dim=arr_sh3.reshape(-1) #to convert n to 1 dimension arrays
print(one_dim)
print()
print(one_dim.ndim)


1
[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

3
[ 1  2  3  4  5  6  7  8  9 10 11 12]

1


# Broadcasting

In [31]:
#Broadcasting will be performed on 2x1 with 2x1 or 2x2 2... 2x2 with 2x2 or 4x2
var=np.array([1,2,3])
var2=([1],[2],[3])
print(var*var2)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [32]:
var1=np.array([[1,2,3],[1,2,3],[1,2,3]])
var3=np.array([1,2,3])
print(var1*var3)

[[1 4 9]
 [1 4 9]
 [1 4 9]]


# slicing 

In [3]:
var=np.array([7,6,5,4,3,3])
print(var[::2])  #print values skipping 1 value in b/w
print(var[::-1]) #reverse an array

[7 5 3]
[3 3 4 5 6 7]


In [5]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
print(var2[1,:]) #print all the elements of row 2

[5 6 7 8]


In [6]:
var3=np.array([[[1,2,3,4,5],[24,56,6,7,8]],[[9,8,7,6,5],[3,4,6,7,1]]])
print(var3[1,0,3]) 


6


# iteration

In [10]:
var=np.array([7,6,5,4,3,3])
for i in var:
    print(i)

7
6
5
4
3
3


In [14]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
for i in var2:
    for l in i:
     print(l)

1
2
3
4
5
6
7
8


In [23]:
var2=np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,1,4],[3,7,6,4]]])
for i in var2:
 for l in i:
    for k in l:
      print(k)

1
2
3
4
5
6
7
8
2
3
1
4
3
7
6
4


In [2]:
var2=np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,1,4],[3,7,6,4]]])
for i in np.nditer(var2):
    print(i)

1
2
3
4
5
6
7
8
2
3
1
4
3
7
6
4


In [7]:


arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='F'): #ROW Major order C And column major order F nditer to not use more and more for loops
    print(element)

1
3
2
4


In [9]:


arr = np.array([[1, 2], [3, 4]])

for element in np.ndenumerate(arr): 
    print(element)

((0, 0), 1)
((0, 1), 2)
((1, 0), 3)
((1, 1), 4)


In [2]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [3]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}") #When ndenumerate is called with a NumPy array as an argument, it creates an iterator. When you iterate over this object (e.g., in a for loop), it yields a tuple for each element in the array. This tuple contains two items:

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4


# nditer 


Modifying Array Values:
Enables in-place modification of array elements by specifying readwrite or writeonly flags for operands. 
When modifying, the nditer should be used as a context manager (with statement) or its close() method should be called 
to ensure changes are written back to the original array.

In [10]:
arr = np.array([[1, 2], [3, 4]])
print("orignal arr:")
for i in arr:
    print(i)
print()
print("Modification in oignal array")
with np.nditer(arr,op_flags=["readwrite"]) as it:
        for k in arr:
            k[...]=k*2 #modify in place orignal array
            print(arr)

orignal arr:
[1 2]
[3 4]

Modification in oignal array
[[2 4]
 [3 4]]
[[2 4]
 [6 8]]


In [7]:
for i in arr:
    print(i)

[2 4]
[6 8]


# copy vs view 

copy means creating a new array and view means viewing the orignal array any changes made in view will be made in org arry

In [2]:
arr = np.array([[1, 2], [3, 4]])
cop=arr.copy()
print("orignal:",arr)
print("copy:",cop)

orignal: [[1 2]
 [3 4]]
copy: [[1 2]
 [3 4]]


In [9]:
arr = np.array([[1, 2],[3, 4]])
vw=arr.view()
with np.nditer(vw,op_flags=['readwrite']) as it:
  for i in it:
    i[...]=i*2
print("orignal:",arr)
print("view:",vw)

orignal: [[2 4]
 [6 8]]
view: [[2 4]
 [6 8]]


# joining arrays using 1.concatenate,2.stack(hstack,vstack,dstack,axis=0,axis=1)

In [5]:
arr = np.array([[1, 2],[3, 4]])
arr_1 = np.array([[0, 2],[8, 5]])
print(np.concatenate((arr,arr_1),axis=1)) #along the row
print(np.concatenate((arr,arr_1),axis=0)) #along the column

[[1 2 0 2]
 [3 4 8 5]]
[[1 2]
 [3 4]
 [0 2]
 [8 5]]


In [7]:
arr = np.array([[1, 2],[3, 4]])
arr_1 = np.array([[0, 2],[8, 5]])
print(np.stack((arr,arr_1),axis=1))
print(np.vstack((arr,arr_1))) #column
print(np.hstack((arr,arr_1))) #row
print(np.dstack((arr,arr_1))) #height

[[[1 2]
  [0 2]]

 [[3 4]
  [8 5]]]
[[1 2]
 [3 4]
 [0 2]
 [8 5]]
[[1 2 0 2]
 [3 4 8 5]]
[[[1 0]
  [2 2]]

 [[3 8]
  [4 5]]]


# Split Array

In [9]:
arr = np.array([1, 2,3, 4])

print(arr)
print()
print(np.split(arr,2))

[1 2 3 4]

[array([1, 2]), array([3, 4])]


In [16]:
arr = np.array([[1, 2],[3, 4],[3,5]])

print(arr)
print()
print(np.split(arr,2,axis=1))

[[1 2]
 [3 4]
 [3 5]]

[array([[1],
       [3],
       [3]]), array([[2],
       [4],
       [5]])]


# Numpy Array Functions (search,sorted,search sorted,filter)

In [2]:
arr = np.array([1, 2,3, 4,3,5])
print(np.where(arr==3)) #search and return indexes

(array([2, 4], dtype=int64),)


In [3]:
arr = np.array([[1, 2],[3, 4],[3,5]])
print(np.where(arr==3)) #search and return indexes

(array([1, 2], dtype=int64), array([0, 0], dtype=int64))


# searchsorted works like a binary array gives the index where any new particular value could be placed

In [4]:
arr = np.array([1, 2,3,5])
print(np.searchsorted(arr,4)) 
print(np.searchsorted(arr,4,side="right")) 

3


# sort

In [5]:
arr = np.array([1, 23,4,5,6,3,52,0])
print(np.sort(arr))

[ 0  1  3  4  5  6 23 52]


In [8]:
arr_1=np.array(["s","p","d","f"])
print(np.sort(arr_1))

['d' 'f' 'p' 's']


In [12]:
arr = np.array([[[1, 23],[41,5]],[[6,3],[52,0]]])
print(np.sort(arr[0,1]))

[ 5 41]


# Filter Array

In [14]:
arr_1=np.array(["s","p","d","f"])
f=[True,False,True,False]
print(f)
new_n=arr_1[f]
print(new_n)


[True, False, True, False]
['s' 'd']


# shuffle

In [5]:
arr_1=np.array(["s","p","d","f"])
np.random.shuffle(arr_1)
print(arr_1)

['p' 'f' 'd' 's']


In [11]:
arr_1=np.array(["s","p","d","f",'f','p'])
np.unique(arr_1)
print(np.unique(arr_1,return_index=True,return_counts=True))


(array(['d', 'f', 'p', 's'], dtype='<U1'), array([2, 3, 1, 0], dtype=int64), array([1, 2, 2, 1], dtype=int64))


In [12]:
arr_1=np.array(["s","p","d","f",'f','p'])
np.resize(arr_1,(2,3))


array([['s', 'p', 'd'],
       ['f', 'f', 'p']], dtype='<U1')

# flatten / ravel to convert two dimension array into 1 diension

Order could be C F A K 

In [10]:
arr_1=np.array(["s","p","d","f",'f','p'])
y=np.resize(arr_1,(2,3))
print(y)
print()
print("Flatten no parameter of numpy:",y.flatten(order="F"))
print()
print("Ravel parameter of Numpy:",np.ravel(y,order="F"))

[['s' 'p' 'd']
 ['f' 'f' 'p']]

Flatten no parameter of numpy: ['s' 'f' 'p' 'f' 'd' 'p']

Ravel parameter of Numpy: ['s' 'f' 'p' 'f' 'd' 'p']


# insert 

In [3]:
arr_1=np.array(["s","p","d","f",'f','p'])
arr=np.insert(arr_1,3,"e")
print(arr_1)
print()
print(arr)

['s' 'p' 'd' 'f' 'f' 'p']

['s' 'p' 'd' 'e' 'f' 'f' 'p']


Axis 0: This axis runs vertically, down the rows. Operations performed along axis=0 will apply independently to each column.


In [15]:
arr_1=np.array([["s","p"],["d","f"],['f','p']])
arr=np.insert(arr_1,3,"e",axis=0)
ar=np.append(arr_1,[["e","y"]],axis=0)
print(arr_1)
print()
print(arr)
print()
print(ar)

[['s' 'p']
 ['d' 'f']
 ['f' 'p']]

[['s' 'p']
 ['d' 'f']
 ['f' 'p']
 ['e' 'e']]

[['s' 'p']
 ['d' 'f']
 ['f' 'p']
 ['e' 'y']]


Axis 1: This axis runs horizontally, across the columns. Operations performed along axis=1 will apply independently to each row.

In [18]:
arr_1=np.array([["s","p"],["d","f"],['f','p']])
arr=np.insert(arr_1,(1,2),["e","y"],axis=1)
ar=np.append(arr_1,[["e","y"]])
print(arr_1)
print()
print(arr)
print()
print(ar)


[['s' 'p']
 ['d' 'f']
 ['f' 'p']]

[['s' 'e' 'p' 'y']
 ['d' 'e' 'f' 'y']
 ['f' 'e' 'p' 'y']]

['s' 'p' 'd' 'f' 'f' 'p' 'e' 'y']


# delete

In [21]:
del_1=np.delete(arr_1,2)
print(del_1)

['s' 'p' 'f' 'f' 'p']


# Concept of Matrix

In [4]:
var1=np.matrix([[1,2],[1,3]])
var2=np.matrix([[1,2],[1,9]])
print(var1)
print()
print(var1.dot(var2))

[[1 2]
 [1 3]]

[[ 3 20]
 [ 4 29]]


# Matrix functions in numpy arrays

1. Transpose convert rows into column 2.swapaxwes,3.inverse 4.power 5.determinant of matrix

In [20]:
var1=np.matrix([[1,2],[1,3]])
print(var1)
print()
print(np.transpose(var1)) #transpose
print()
print(var1.T) #transpose
print()
print(np.swapaxes(var1,1,0)) #axis 1 to 0 sawapaxes
print()
print(np.linalg.inv(var1)) #inverse
print()
print(np.linalg.matrix_power(var1,3)) #power when n>0 n=power which is 3 in this case
print()
print(np.linalg.matrix_power(var1,-3)) # inverse*power in case of n<0 -3
print()
print(np.linalg.matrix_power(var1,0)) #gives identity matrix
print()
print(np.linalg.det(var1)) #determinant

[[1 2]
 [1 3]]

[[1 1]
 [2 3]]

[[1 1]
 [2 3]]

[[1 1]
 [2 3]]

[[ 3. -2.]
 [-1.  1.]]

[[11 30]
 [15 41]]

[[ 41. -30.]
 [-15.  11.]]

[[1 0]
 [0 1]]

1.0


# handeling missing values

# Nan(not a number) np.isnan() to detect null values

In [6]:
arr=np.array([1,2,3,np.nan,9])
print(np.isnan(arr)) #will return true for null value

[False False False  True False]


if(np.nan==np.nan): #no we cannot compare them directly

In [10]:
cleaned_arr=np.nan_to_num(arr,nan=12) #default value will be zero
print(cleaned_arr)

[ 1.  2.  3. 12.  9.]


# deaing with infinite values

In [12]:
arr_1=([1,2,np.inf,32,-np.inf])
print(np.isinf(arr_1)) #return true or false

[False False  True False  True]


In [14]:
cleaned_arr1=np.nan_to_num(arr_1,posinf=199,neginf=-199) 
print(cleaned_arr1)

[   1.    2.  199.   32. -199.]


# # Read the CSV file into a NumPy array, handling missing values
# data = np.genfromtxt('Employee.csv', delimiter=',', dtype=None, names=True, encoding='utf-8')

# print(data)

In [2]:
import pandas as pd 

In [3]:
data=pd.read_csv("Employee.csv")

In [4]:
print(data)

      Education  JoiningYear       City  PaymentTier   Age  Gender  \
0     Bachelors         2017  Bangalore            3  34.0    Male   
1     Bachelors         2013       Pune            1  28.0  Female   
2     Bachelors         2014  New Delhi            3  38.0  Female   
3       Masters         2016  Bangalore            3  27.0    Male   
4       Masters         2017       Pune            3  24.0    Male   
...         ...          ...        ...          ...   ...     ...   
4648  Bachelors         2013  Bangalore            3  26.0  Female   
4649    Masters         2013       Pune            2  37.0    Male   
4650    Masters         2018  New Delhi            3  27.0    Male   
4651  Bachelors         2012  Bangalore            3  30.0    Male   
4652  Bachelors         2015  Bangalore            3  33.0     NaN   

     EverBenched  ExperienceInCurrentDomain  LeaveOrNot  
0             No                        0.0           0  
1             No                        3.0

In [5]:
data.describe()

JoiningYear  PaymentTier          Age  ExperienceInCurrentDomain  \
count  4653.000000  4653.000000  4652.000000                4652.000000   
mean   2015.062970     2.698259    29.392304                   3.058469   
std       1.863377     0.561435     4.826133                   0.712045   
min    2012.000000     1.000000    22.000000                   0.000000   
25%    2013.000000     3.000000    26.000000                   3.000000   
50%    2015.000000     3.000000    28.000000                   3.000000   
75%    2017.000000     3.000000    32.000000                   3.000000   
max    2018.000000     3.000000    41.000000                   5.000000   

        LeaveOrNot  
count  4653.000000  
mean      0.343864  
std       0.475047  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Education                  4653 non-null   object 
 1   JoiningYear                4653 non-null   int64  
 2   City                       4650 non-null   object 
 3   PaymentTier                4653 non-null   int64  
 4   Age                        4652 non-null   float64
 5   Gender                     4651 non-null   object 
 6   EverBenched                4651 non-null   object 
 7   ExperienceInCurrentDomain  4652 non-null   float64
 8   LeaveOrNot                 4653 non-null   int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 327.3+ KB


In [24]:
print("Missing values in each column:")
print(data.isnull().sum())

Missing values in each column:
Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64


In [8]:
data['ExperienceInCurrentDomain'].fillna(data['ExperienceInCurrentDomain'].mean(), inplace=True)# With inplace=True (no assignment needed)

C:\Users\A I TECH\AppData\Local\Temp\ipykernel_1100\3880802651.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['ExperienceInCurrentDomain'].fillna(data['ExperienceInCurrentDomain'].mean(), inplace=True)# With inplace=True (no assignment needed)


In [13]:
data['City'].fillna(data['City'].mode()[0], inplace=True)

In [15]:
data['Age'].fillna(data['Age'].mean(), inplace=True)# With inplace=True (no assignment needed)

C:\Users\A I TECH\AppData\Local\Temp\ipykernel_1100\3647552776.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(), inplace=True)# With inplace=True (no assignment needed)


# dealing with infinite values 

In [17]:
data.replace((np.inf,-np.inf),np.nan,inplace=True) 

In [18]:
data.fillna(data.mean(),inplace=True) #if we have numerical dataframe in our dataset

TypeError: can only concatenate str (not "int") to str

# lets drop gender dataframe missing rows

In [21]:
data.dropna(subset=["Gender"],axis=0,inplace=True)

In [23]:
data['EverBenched'].fillna(data['EverBenched'].mode()[0], inplace=True)

C:\Users\A I TECH\AppData\Local\Temp\ipykernel_1100\2998504357.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['EverBenched'].fillna(data['EverBenched'].mode()[0], inplace=True)


# Drop Duplicates

In [26]:
data.drop_duplicates(inplace=True)  # Drop duplicate rows based on all columns

# lets deals with negative values

In [27]:
data["Age"]=np.where(data["Age"]<0,data["Age"].mean(),data["Age"])

# lets save cleaned data set

In [28]:
data.to_csv("cleaned.csv",index=False)
print("Cleaned data and saved successfuly!")

Cleaned data and saved successfuly!
